@hostname = 127.0.0.1
@port = 8080
@host = http://{{hostname}}:{{port}}
@contentType = application/json

### ユーザ登録

POST {{host}}/management/user HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "sample02",
    "address": "ab",
    "birthday": "2020-01-01T00:00:00Z",
    "email": "sample02@sample.com"
}

### ユーザ削除

DELETE {{host}}/management/user/123e4567-e89b-12d3-a456-426614174000 HTTP/1.1

### ユーザ検索

GET {{host}}/user/123e4567-e89b-12d3-a456-426614174000 HTTP/1.1